spring.application.name=document-verification-service

server.port=8080

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/document_verification_api
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Redis Cache
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

# AWS S3
#aws.s3.region=us-east-1
#aws.s3.bucket-name=

aws.s3.endpoint=http://localhost:9000
aws.s3.region=us-east-1
aws.s3.access-key=minioadmin
aws.s3.secret-key=minioadmin123
aws.s3.bucket=documents

# Resilience4j
resilience4j.circuitbreaker.instances.default.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.default.wait-duration-in-open-state=60s
resilience4j.circuitbreaker.instances.default.sliding-window-size=10

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
